import { db } from '@/lib/db';
import { hashPassword } from '@/lib/auth';

const DEMO_USER_EMAIL = 'demo@bookmarkvault.app';
const DEMO_USER_PASSWORD = 'password';

const COLLECTIONS = [
  { name: 'Tech & AI', description: 'Latest developments in technology and artificial intelligence', color: '#10b981', icon: '💻' },
  { name: 'Design Inspiration', description: 'UI/UX design patterns, typography, and visual inspiration', color: '#f59e0b', icon: '🎨' },
  { name: 'Startup Wisdom', description: 'Insights from founders, VCs, and the startup ecosystem', color: '#ef4444', icon: '🚀' },
  { name: 'Data Science', description: 'Machine learning, data engineering, and analytics', color: '#8b5cf6', icon: '📊' },
  { name: 'Creative Ideas', description: 'Creative projects, art, and innovative concepts', color: '#ec4899', icon: '✨' },
];

const TAGS = [
  { name: 'AI', color: '#10b981' },
  { name: 'Machine Learning', color: '#059669' },
  { name: 'Design', color: '#f59e0b' },
  { name: 'Startup', color: '#ef4444' },
  { name: 'TypeScript', color: '#3b82f6' },
  { name: 'React', color: '#06b6d4' },
  { name: 'Python', color: '#8b5cf6' },
  { name: 'Open Source', color: '#6366f1' },
  { name: 'Productivity', color: '#f97316' },
  { name: 'Web3', color: '#a855f7' },
  { name: 'Career', color: '#14b8a6' },
  { name: 'DevOps', color: '#64748b' },
];

interface BookmarkData {
  content: string;
  xPostId: string;
  xAuthorName: string;
  xAuthorUsername: string;
  xAuthorAvatar: string | null;
  mediaTypes: string[];
  mediaUrls: string[];
  replyCount: number;
  repostCount: number;
  likeCount: number;
  viewCount: number;
  bookmarkCount: number;
  postedAt: Date;
  collectionIndices: number[];
  tagIndices: number[];
}

const BOOKMARKS: BookmarkData[] = [
  {
    content: 'Just published our research on scaling laws for language models. The key insight: compute-optimal training requires balancing model size and data size much more carefully than previously thought. The Chinchilla paper changed everything. 📄',
    xPostId: 'seed_001',
    xAuthorName: 'Alex Chen',
    xAuthorUsername: 'alexchen_ml',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 234,
    repostCount: 1892,
    likeCount: 8432,
    viewCount: 234000,
    bookmarkCount: 3210,
    postedAt: new Date('2025-01-15T10:30:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'The new CSS @starting-style rule is a game-changer for animations. No more hacky workarounds for animating elements from display:none. Here\'s a quick demo showing smooth entry animations 🎬',
    xPostId: 'seed_002',
    xAuthorName: 'Sarah Drasner',
    xAuthorUsername: 'sarah_edo',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/css-anim/800/400'],
    replyCount: 89,
    repostCount: 567,
    likeCount: 3421,
    viewCount: 89000,
    bookmarkCount: 1543,
    postedAt: new Date('2025-01-14T15:20:00Z'),
    collectionIndices: [1],
    tagIndices: [2, 5],
  },
  {
    content: 'We just raised our Series B! $45M to build the future of AI-powered code review. Grateful to our investors and incredible team. 2025 is going to be massive. 🚀',
    xPostId: 'seed_003',
    xAuthorName: 'Jason Liu',
    xAuthorUsername: 'jasonliu_dev',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 456,
    repostCount: 2341,
    likeCount: 12890,
    viewCount: 567000,
    bookmarkCount: 4321,
    postedAt: new Date('2025-01-13T09:00:00Z'),
    collectionIndices: [2],
    tagIndices: [3, 0],
  },
  {
    content: 'Hot take: The best engineers I\'ve worked with spend 70% of their time reading code and 30% writing it. Understanding existing systems deeply before making changes is the highest-leverage skill in software.',
    xPostId: 'seed_004',
    xAuthorName: 'Kelsey Hightower',
    xAuthorUsername: 'kelseyhightower',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 312,
    repostCount: 4521,
    likeCount: 19876,
    viewCount: 890000,
    bookmarkCount: 7654,
    postedAt: new Date('2025-01-12T14:30:00Z'),
    collectionIndices: [2],
    tagIndices: [8, 10],
  },
  {
    content: 'Built a real-time collaborative whiteboard using CRDTs and WebRTC. The sync algorithm handles conflicts beautifully - even with 20+ concurrent users. Open-sourcing it this week! 🎉',
    xPostId: 'seed_005',
    xAuthorName: 'Eve Martinez',
    xAuthorUsername: 'evemartinez_',
    xAuthorAvatar: null,
    mediaTypes: ['video'],
    mediaUrls: ['https://picsum.photos/seed/whiteboard/800/450'],
    replyCount: 178,
    repostCount: 890,
    likeCount: 5678,
    viewCount: 234000,
    bookmarkCount: 2109,
    postedAt: new Date('2025-01-11T16:45:00Z'),
    collectionIndices: [0, 1],
    tagIndices: [7, 5],
  },
  {
    content: 'The Transformer architecture is 8 years old. In that time, it went from "Attention is All You Need" to powering everything from GPT-4 to protein folding. What a journey. Here\'s my thread on the 10 most important papers since then 🧵',
    xPostId: 'seed_006',
    xAuthorName: 'Andrej Karpathy',
    xAuthorUsername: 'karpathy',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 6789,
    likeCount: 34567,
    viewCount: 1230000,
    bookmarkCount: 12345,
    postedAt: new Date('2025-01-10T11:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'Finally figured out the perfect Figma-to-code workflow: 1) Design tokens as JSON 2) Style Dictionary for transforms 3) CSS custom properties output 4) Tailwind plugin for utility classes. Zero manual sync needed! 🎨➡️💻',
    xPostId: 'seed_007',
    xAuthorName: 'Mia Wang',
    xAuthorUsername: 'miawang_design',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/figma-code/800/400'],
    replyCount: 145,
    repostCount: 678,
    likeCount: 4321,
    viewCount: 156000,
    bookmarkCount: 1876,
    postedAt: new Date('2025-01-09T13:20:00Z'),
    collectionIndices: [1],
    tagIndices: [2, 5],
  },
  {
    content: 'RAG is not dead. But naive RAG is. The difference between production RAG and demo RAG: chunking strategy, hybrid search, reranking, query decomposition, and self-correction. Built a production pipeline that achieves 95% accuracy vs 60% for naive approach.',
    xPostId: 'seed_008',
    xAuthorName: 'Jerry Wei',
    xAuthorUsername: 'jerrywei_ai',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/rag-pipeline/800/500'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3456,
    postedAt: new Date('2025-01-08T10:15:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1, 6],
  },
  {
    content: 'PSA: Your startup doesn\'t need Kubernetes. Start with a single server. Scale when you have actual traffic. Premature optimization isn\'t just for code - it applies to infrastructure too. I\'ve seen too many teams waste months on k8s for 100 req/day.',
    xPostId: 'seed_009',
    xAuthorName: 'DHH',
    xAuthorUsername: 'dhh',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 890,
    repostCount: 3456,
    likeCount: 15678,
    viewCount: 890000,
    bookmarkCount: 5678,
    postedAt: new Date('2025-01-07T08:30:00Z'),
    collectionIndices: [2],
    tagIndices: [3, 11],
  },
  {
    content: 'The Python 3.13 release is incredible. Free-threaded mode (no GIL!), improved error messages, JIT compiler experimental. The performance gains are real - seeing 2-3x speedups on CPU-bound workloads. Python is becoming a serious performance contender.',
    xPostId: 'seed_010',
    xAuthorName: 'Guido van Rossum',
    xAuthorUsername: 'gvanrossum',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 345,
    repostCount: 2345,
    likeCount: 11234,
    viewCount: 567000,
    bookmarkCount: 4567,
    postedAt: new Date('2025-01-06T12:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [6],
  },
  {
    content: 'My design system just hit 10,000 GitHub stars! Started as a side project to learn React compound components. Key lessons: 1) API design matters more than features 2) Accessibility first, not after 3) Documentation IS the product 🌟',
    xPostId: 'seed_011',
    xAuthorName: 'Lee Robinson',
    xAuthorUsername: 'leeerob',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/design-system/800/450'],
    replyCount: 234,
    repostCount: 890,
    likeCount: 6789,
    viewCount: 234000,
    bookmarkCount: 2345,
    postedAt: new Date('2025-01-05T17:30:00Z'),
    collectionIndices: [1],
    tagIndices: [2, 5, 7],
  },
  {
    content: 'Transformers meet diffusion: our new paper shows how transformer attention patterns can dramatically improve image generation quality. 40% better FID scores on ImageNet with 2x fewer parameters. The convergence of modalities continues! 🔥',
    xPostId: 'seed_012',
    xAuthorName: 'Fei-Fei Li',
    xAuthorUsername: 'drfeifei',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/diffusion-tf/800/500'],
    replyCount: 456,
    repostCount: 2345,
    likeCount: 12345,
    viewCount: 456000,
    bookmarkCount: 4567,
    postedAt: new Date('2025-01-04T09:45:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'Shipped v2.0 of our open-source monitoring tool! New features: distributed tracing, log correlation, AI-powered anomaly detection, and a beautiful new dashboard. All free and self-hosted. Check it out! 🎉',
    xPostId: 'seed_013',
    xAuthorName: 'Nina Patel',
    xAuthorUsername: 'ninapatel_ops',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/monitoring/800/400'],
    replyCount: 123,
    repostCount: 567,
    likeCount: 3456,
    viewCount: 123000,
    bookmarkCount: 1567,
    postedAt: new Date('2025-01-03T14:00:00Z'),
    collectionIndices: [0],
    tagIndices: [7, 11],
  },
  {
    content: 'The future of work is not remote OR office. It\'s async-first with intentional in-person moments. After 4 years of running a distributed company, here are the 7 principles that made it work for 200+ people 🧵',
    xPostId: 'seed_014',
    xAuthorName: 'Brian Chesky',
    xAuthorUsername: 'bchesky',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 678,
    repostCount: 3456,
    likeCount: 18901,
    viewCount: 678000,
    bookmarkCount: 6543,
    postedAt: new Date('2025-01-02T11:30:00Z'),
    collectionIndices: [2],
    tagIndices: [3, 8],
  },
  {
    content: 'Generative art exploration: Using flow fields with Perlin noise to create organic, nature-inspired patterns. Each piece is unique based on the random seed. The intersection of math and art never gets old 🌊',
    xPostId: 'seed_015',
    xAuthorName: 'Tyler Hobbs',
    xAuthorUsername: 'tylerxhobbs',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/gen-art/800/800'],
    replyCount: 89,
    repostCount: 456,
    likeCount: 5678,
    viewCount: 178000,
    bookmarkCount: 2109,
    postedAt: new Date('2025-01-01T16:00:00Z'),
    collectionIndices: [4],
    tagIndices: [2],
  },
  {
    content: 'LLM agents are overrated for most tasks. Good prompt engineering + structured output + simple tool calling beats complex agent frameworks 9/10 times. Keep it simple, measure everything, and only add complexity when you have evidence you need it.',
    xPostId: 'seed_016',
    xAuthorName: 'Simon Willison',
    xAuthorUsername: 'simonw',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 2345,
    likeCount: 14567,
    viewCount: 567000,
    bookmarkCount: 5432,
    postedAt: new Date('2024-12-31T10:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0],
  },
  {
    content: 'TypeScript 5.7 just dropped and the type system keeps getting more powerful. Template literal types, satisfies operator improvements, and better inference. If you\'re still writing plain JS, you\'re missing out on the best DX in web dev.',
    xPostId: 'seed_017',
    xAuthorName: 'Matt Pocock',
    xAuthorUsername: 'mattpocockuk',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3210,
    postedAt: new Date('2024-12-30T13:45:00Z'),
    collectionIndices: [0],
    tagIndices: [4],
  },
  {
    content: 'Redesigned our entire onboarding flow. Went from 23% completion to 67% by: 1) Removing 4 unnecessary steps 2) Adding progress indicators 3) Making it feel like a conversation, not a form. Sometimes less is more. 📐',
    xPostId: 'seed_018',
    xAuthorName: 'Julie Zhuo',
    xAuthorUsername: 'joulee',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/onboarding/800/450'],
    replyCount: 345,
    repostCount: 1890,
    likeCount: 9876,
    viewCount: 456000,
    bookmarkCount: 3789,
    postedAt: new Date('2024-12-29T15:30:00Z'),
    collectionIndices: [1, 2],
    tagIndices: [2, 3],
  },
  {
    content: 'Fine-tuning LLMs on your own data is now trivially easy. Our open-source tool lets you do it in 3 commands: extract, train, deploy. Just fine-tuned Llama 3.1 on our support tickets - 85% resolution rate vs 40% with base model. 🤖',
    xPostId: 'seed_019',
    xAuthorName: 'Hamel Husain',
    xAuthorUsername: 'hamelhusain',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 189,
    repostCount: 987,
    likeCount: 5432,
    viewCount: 234000,
    bookmarkCount: 2109,
    postedAt: new Date('2024-12-28T09:15:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1, 6],
  },
  {
    content: 'The most underrated skill in tech: writing. Not code - plain English. Being able to write clear RFCs, docs, and proposals will 10x your impact. Every senior engineer I know is also an excellent writer.',
    xPostId: 'seed_020',
    xAuthorName: 'Gergely Orosz',
    xAuthorUsername: 'gergelyorosz',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 456,
    repostCount: 3456,
    likeCount: 16789,
    viewCount: 789000,
    bookmarkCount: 6789,
    postedAt: new Date('2024-12-27T11:00:00Z'),
    collectionIndices: [2],
    tagIndices: [8, 10],
  },
  {
    content: 'WebGPU is production-ready! Just shipped our first WebGPU-powered data visualization dashboard. 60fps with 1M+ data points. The performance gap between native and web is closing fast. Here\'s how we did it 🧵',
    xPostId: 'seed_021',
    xAuthorName: 'Riccardo Scalco',
    xAuthorUsername: 'riccardoscalco',
    xAuthorAvatar: null,
    mediaTypes: ['video'],
    mediaUrls: ['https://picsum.photos/seed/webgpu-viz/800/450'],
    replyCount: 123,
    repostCount: 567,
    likeCount: 3456,
    viewCount: 156000,
    bookmarkCount: 1543,
    postedAt: new Date('2024-12-26T14:20:00Z'),
    collectionIndices: [0, 1],
    tagIndices: [5, 4],
  },
  {
    content: 'Stop building features nobody asked for. Talk to your users. Not in surveys - actual conversations. Spend 30% of your time on user research. The ROI is insane. We pivoted our entire product based on 10 customer interviews and 10x\'d our growth.',
    xPostId: 'seed_022',
    xAuthorName: 'Lenny Rachitsky',
    xAuthorUsername: 'lennysan',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 2345,
    likeCount: 13456,
    viewCount: 678000,
    bookmarkCount: 5432,
    postedAt: new Date('2024-12-25T10:00:00Z'),
    collectionIndices: [2],
    tagIndices: [3],
  },
  {
    content: 'New blog post: How we reduced our AWS bill by 70% with these 5 optimizations. Spoiler: reserved instances, S3 intelligent tiering, Lambda power tuning, and actually reading the billing dashboard. $340K annual savings. 💰',
    xPostId: 'seed_023',
    xAuthorName: 'Corey Quinn',
    xAuthorUsername: 'quinnypig',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 345,
    repostCount: 1890,
    likeCount: 8765,
    viewCount: 345000,
    bookmarkCount: 3456,
    postedAt: new Date('2024-12-24T12:30:00Z'),
    collectionIndices: [0],
    tagIndices: [11, 8],
  },
  {
    content: 'The intersection of AI and design tools is fascinating. Our new plugin generates UI components from natural language descriptions. Not templates - actual custom components with proper semantic HTML and accessibility built in. 🎨✨',
    xPostId: 'seed_024',
    xAuthorName: 'Elizabeth Lin',
    xAuthorUsername: 'elizaboriLin',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/ai-design/800/500'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 6789,
    viewCount: 234000,
    bookmarkCount: 2345,
    postedAt: new Date('2024-12-23T16:45:00Z'),
    collectionIndices: [1],
    tagIndices: [0, 2],
  },
  {
    content: 'Vector databases comparison: We benchmarked Pinecone, Weaviate, Qdrant, Milvus, and pgvector on the same dataset (10M embeddings). Results surprised us - pgvector was competitive for most use cases. Full results in thread 🧵',
    xPostId: 'seed_025',
    xAuthorName: 'Sam Partee',
    xAuthorUsername: 'sampartee',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/vectordb/800/400'],
    replyCount: 456,
    repostCount: 2345,
    likeCount: 11234,
    viewCount: 456000,
    bookmarkCount: 4321,
    postedAt: new Date('2024-12-22T09:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'After 3 years of working on it, I\'m open-sourcing my creative coding toolkit! WebGL shaders, particle systems, audio reactivity - all with a beautiful API. Inspired by Processing but built for the modern web. ❤️',
    xPostId: 'seed_026',
    xAuthorName: 'Char Stiles',
    xAuthorUsername: 'charstiles',
    xAuthorAvatar: null,
    mediaTypes: ['video'],
    mediaUrls: ['https://picsum.photos/seed/creative-coding/800/450'],
    replyCount: 178,
    repostCount: 890,
    likeCount: 5678,
    viewCount: 189000,
    bookmarkCount: 2109,
    postedAt: new Date('2024-12-21T17:00:00Z'),
    collectionIndices: [4, 1],
    tagIndices: [7, 2],
  },
  {
    content: 'MLOps in 2025: The stack has converged. MLflow for experiment tracking, Kubernetes for training, Ray for distributed compute, and feature stores for serving. Stop building custom solutions - use the standard stack and focus on model quality.',
    xPostId: 'seed_027',
    xAuthorName: 'Chip Huyen',
    xAuthorUsername: 'chipro',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3210,
    postedAt: new Date('2024-12-20T10:30:00Z'),
    collectionIndices: [3],
    tagIndices: [1, 11],
  },
  {
    content: 'The Next.js 15 App Router is finally mature enough for production. We migrated our 500k MAU app and the DX improvement is massive. Server components actually make sense now. React Server Actions are underrated.',
    xPostId: 'seed_028',
    xAuthorName: 'Delba de Oliveira',
    xAuthorUsername: 'delba_oliveira',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 345,
    repostCount: 1890,
    likeCount: 9876,
    viewCount: 456000,
    bookmarkCount: 3789,
    postedAt: new Date('2024-12-19T13:00:00Z'),
    collectionIndices: [0],
    tagIndices: [4, 5],
  },
  {
    content: 'Built a personal knowledge graph from my 5000+ bookmarks using embeddings + knowledge extraction. Now I can query my own reading history in natural language. "What did I save about distributed systems last month?" → instant, accurate results. 🧠',
    xPostId: 'seed_029',
    xAuthorName: 'Andy Matuschak',
    xAuthorUsername: 'andy_matuschak',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/knowledge-graph/800/450'],
    replyCount: 567,
    repostCount: 2345,
    likeCount: 12345,
    viewCount: 567000,
    bookmarkCount: 4567,
    postedAt: new Date('2024-12-18T11:15:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 8],
  },
  {
    content: 'Announcing our seed round! $5M to build the Figma for data. Spreadsheets are 40 years old - it\'s time for something better. We\'re hiring engineers who love both design and data. DMs open! 🚀',
    xPostId: 'seed_030',
    xAuthorName: 'David Khandelwal',
    xAuthorUsername: 'davidkh_data',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 234,
    repostCount: 890,
    likeCount: 4567,
    viewCount: 178000,
    bookmarkCount: 1876,
    postedAt: new Date('2024-12-17T09:30:00Z'),
    collectionIndices: [2, 3],
    tagIndices: [3, 2],
  },
  {
    content: 'Multimodal AI is the next frontier. Our model processes text, images, audio, and video simultaneously with a unified transformer architecture. One model, one set of weights, any modality. The results are mind-blowing. 🔮',
    xPostId: 'seed_031',
    xAuthorName: 'Yann LeCun',
    xAuthorUsername: 'ylecun',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/multimodal/800/500'],
    replyCount: 890,
    repostCount: 4567,
    likeCount: 23456,
    viewCount: 890000,
    bookmarkCount: 8765,
    postedAt: new Date('2024-12-16T10:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'Color theory cheat sheet for developers who can\'t design: 1) Start with 1 brand color 2) Use 60-30-10 rule 3) Check contrast ratios 4) Steal palettes from nature 5) Test in both light and dark mode. Saved my life as a solo founder! 🎨',
    xPostId: 'seed_032',
    xAuthorName: 'Tracy Osborn',
    xAuthorUsername: 'limedaring',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/color-theory/800/600'],
    replyCount: 456,
    repostCount: 2345,
    likeCount: 11234,
    viewCount: 456000,
    bookmarkCount: 4567,
    postedAt: new Date('2024-12-15T14:30:00Z'),
    collectionIndices: [1],
    tagIndices: [2],
  },
  {
    content: 'Decentralized identity is solving real problems. Our DID-based authentication system just passed 1M verifications. No passwords, no email verification, instant onboarding. Web3 infrastructure serving Web2 use cases. 🌐',
    xPostId: 'seed_033',
    xAuthorName: 'Vitalik Buterin',
    xAuthorUsername: 'VitalikButerin',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 1234,
    repostCount: 5678,
    likeCount: 34567,
    viewCount: 1230000,
    bookmarkCount: 9876,
    postedAt: new Date('2024-12-14T08:00:00Z'),
    collectionIndices: [0],
    tagIndices: [9],
  },
  {
    content: 'React Server Components changed how I think about data fetching. No more useEffect spaghetti. No more loading states for data that could be server-rendered. The mental model is simpler, not more complex. Here\'s my complete guide 📚',
    xPostId: 'seed_034',
    xAuthorName: 'Josh Comeau',
    xAuthorUsername: 'joshwcomeau',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 345,
    repostCount: 2345,
    likeCount: 12345,
    viewCount: 456000,
    bookmarkCount: 4567,
    postedAt: new Date('2024-12-13T12:00:00Z'),
    collectionIndices: [0],
    tagIndices: [5, 4],
  },
  {
    content: 'We trained a 1B parameter model that outperforms GPT-3.5 on domain-specific tasks. The secret? High-quality domain data + careful data curation + evaluation-driven development. Size isn\'t everything - data quality is. 📊',
    xPostId: 'seed_035',
    xAuthorName: 'Raza Habib',
    xAuthorUsername: 'razorhabib',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/small-model/800/400'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3210,
    postedAt: new Date('2024-12-12T10:45:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'Creative coding tip: Use sine waves for everything. Movement, color, scale, rotation - sine waves create natural-feeling patterns. Layer multiple frequencies for complexity. Add a little noise for organic feel. That\'s it, that\'s the workshop. 🌊',
    xPostId: 'seed_036',
    xAuthorName: 'Bees and Bombs',
    xAuthorUsername: 'beesandbombs',
    xAuthorAvatar: null,
    mediaTypes: ['gif'],
    mediaUrls: ['https://picsum.photos/seed/sine-waves/800/800'],
    replyCount: 89,
    repostCount: 567,
    likeCount: 4567,
    viewCount: 156000,
    bookmarkCount: 1876,
    postedAt: new Date('2024-12-11T16:00:00Z'),
    collectionIndices: [4],
    tagIndices: [2],
  },
  {
    content: 'PostgreSQL 17 is here and it\'s a big one: logical replication improvements, SQL/JSON features, incremental sort for aggregates, and much better performance for heavy workloads. The most underrated database just keeps getting better. 🐘',
    xPostId: 'seed_037',
    xAuthorName: 'Craig Kerstiens',
    xAuthorUsername: 'craigkerstiens',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 178,
    repostCount: 890,
    likeCount: 5678,
    viewCount: 234000,
    bookmarkCount: 2345,
    postedAt: new Date('2024-12-10T09:30:00Z'),
    collectionIndices: [0],
    tagIndices: [11],
  },
  {
    content: 'The best career advice I ever got: "Spend 2 years learning, 2 years doing, and 2 years teaching. Then repeat." The teaching phase is where you develop real expertise and build your network. It\'s not selfish to share what you know.',
    xPostId: 'seed_038',
    xAuthorName: 'Cassidy Williams',
    xAuthorUsername: 'cassidoo',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 3456,
    likeCount: 15678,
    viewCount: 567000,
    bookmarkCount: 5678,
    postedAt: new Date('2024-12-09T11:00:00Z'),
    collectionIndices: [2],
    tagIndices: [10, 8],
  },
  {
    content: 'Our data pipeline processes 10TB/day with 99.99% reliability. Architecture: Kafka for ingestion, Flink for streaming, Iceberg for storage, dbt for transformation, and Great Expectations for quality. Built by a team of 4. Here\'s the breakdown 🧵',
    xPostId: 'seed_039',
    xAuthorName: 'Maxime Beauchemin',
    xAuthorUsername: 'mabou',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/data-pipeline/800/450'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3456,
    postedAt: new Date('2024-12-08T14:15:00Z'),
    collectionIndices: [3],
    tagIndices: [1, 11],
  },
  {
    content: 'The most beautiful loading animation I\'ve ever seen. This is what happens when engineers care about design. Every pixel matters. Every millisecond matters. The difference between good and great is in the details. 👌',
    xPostId: 'seed_040',
    xAuthorName: 'Steve Schoger',
    xAuthorUsername: 'steveschoger',
    xAuthorAvatar: null,
    mediaTypes: ['gif'],
    mediaUrls: ['https://picsum.photos/seed/loading-anim/800/400'],
    replyCount: 345,
    repostCount: 2345,
    likeCount: 11234,
    viewCount: 456000,
    bookmarkCount: 4321,
    postedAt: new Date('2024-12-07T15:00:00Z'),
    collectionIndices: [1],
    tagIndices: [2],
  },
  {
    content: 'TIL: You can use CSS scroll-driven animations to create scroll-linked effects without any JavaScript. The `animation-timeline: scroll()` property is supported in all major browsers now. Progressive enhancement at its finest! 🎉',
    xPostId: 'seed_041',
    xAuthorName: 'Bramus Van Damme',
    xAuthorUsername: 'bramus',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/scroll-anim/800/400'],
    replyCount: 178,
    repostCount: 890,
    likeCount: 5678,
    viewCount: 234000,
    bookmarkCount: 2345,
    postedAt: new Date('2024-12-06T10:30:00Z'),
    collectionIndices: [0, 1],
    tagIndices: [5, 2],
  },
  {
    content: 'Just shipped AI-powered error categorization in our monitoring tool. It groups similar errors, suggests root causes, and even recommends fixes from your codebase. Debugging time reduced by 60% in our beta. The AI reads your stack traces so you don\'t have to. 🔍',
    xPostId: 'seed_042',
    xAuthorName: 'Lauri Järvilehto',
    xAuthorUsername: 'laurijarvilehto',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 123,
    repostCount: 567,
    likeCount: 3456,
    viewCount: 123000,
    bookmarkCount: 1543,
    postedAt: new Date('2024-12-05T12:00:00Z'),
    collectionIndices: [0],
    tagIndices: [0, 11],
  },
  {
    content: 'The pomodoro technique is overrated for creative work. Deep creative flow needs uninterrupted 2-3 hour blocks. I switched to "deep work mornings + admin afternoons" and my output doubled. Protect your maker schedule fiercely. ⏰',
    xPostId: 'seed_043',
    xAuthorName: 'Cal Newport',
    xAuthorUsername: 'calnewport',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 789,
    repostCount: 3456,
    likeCount: 16789,
    viewCount: 789000,
    bookmarkCount: 6543,
    postedAt: new Date('2024-12-04T09:00:00Z'),
    collectionIndices: [2],
    tagIndices: [8],
  },
  {
    content: 'Open-sourced our Python library for building AI agents with tool use. Think LangChain but minimal and opinionated. 200 lines of core code, full type safety, streaming support, and works with any LLM. Simple is beautiful. 🐍',
    xPostId: 'seed_044',
    xAuthorName: 'Harrison Chase',
    xAuthorUsername: 'hwchase17',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 2345,
    likeCount: 12345,
    viewCount: 456000,
    bookmarkCount: 4567,
    postedAt: new Date('2024-12-03T11:30:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 6, 7],
  },
  {
    content: 'Generative UI is the next paradigm. Instead of text responses, AI generates interactive React components. Our framework maps LLM outputs to your design system. Imagine asking "show me my metrics" and getting a live dashboard. That\'s where we\'re headed. 🖥️',
    xPostId: 'seed_045',
    xAuthorName: 'Aydrian Howard',
    xAuthorUsername: 'aydrianh',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/gen-ui/800/500'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3210,
    postedAt: new Date('2024-12-02T14:00:00Z'),
    collectionIndices: [0, 1],
    tagIndices: [0, 5],
  },
  {
    content: 'Excited to announce I\'m joining YC as a Visiting Partner! I\'ve reviewed 5000+ applications and here\'s the #1 mistake founders make: building before talking to users. Your MVP should be a conversation, not a product. Validate first, build second. 🎯',
    xPostId: 'seed_046',
    xAuthorName: 'Michael Seibel',
    xAuthorUsername: 'mwseibel',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 890,
    repostCount: 4567,
    likeCount: 23456,
    viewCount: 890000,
    bookmarkCount: 8765,
    postedAt: new Date('2024-12-01T10:00:00Z'),
    collectionIndices: [2],
    tagIndices: [3],
  },
  {
    content: 'The future of CSS is wild. Scroll-driven animations, view transitions, container queries, cascade layers, nesting, :has() selector - all shipped in the last year. CSS is evolving faster than ever and it\'s amazing. 🎨',
    xPostId: 'seed_047',
    xAuthorName: 'Adam Argyle',
    xAuthorUsername: 'argyleink',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/future-css/800/450'],
    replyCount: 345,
    repostCount: 1890,
    likeCount: 9876,
    viewCount: 345000,
    bookmarkCount: 3789,
    postedAt: new Date('2024-11-30T13:30:00Z'),
    collectionIndices: [1],
    tagIndices: [2, 5],
  },
  {
    content: 'Thought experiment: What if your IDE could predict what you\'re going to type next with 95% accuracy? Not autocomplete - actual understanding of your intent. We\'re building it. Early results are promising. AI-assisted coding is just getting started. 💡',
    xPostId: 'seed_048',
    xAuthorName: 'Aman Sanger',
    xAuthorUsername: 'amansanger',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 567,
    repostCount: 2345,
    likeCount: 11234,
    viewCount: 456000,
    bookmarkCount: 4321,
    postedAt: new Date('2024-11-29T09:00:00Z'),
    collectionIndices: [0, 2],
    tagIndices: [0, 4],
  },
  {
    content: 'Data viz of the day: Animated treemap showing how tech company valuations changed over the last decade. Apple went from $500B to $3.5T. The scale of value creation is staggering. 📈',
    xPostId: 'seed_049',
    xAuthorName: 'Nadieh Bremer',
    xAuthorUsername: 'NadiehBremer',
    xAuthorAvatar: null,
    mediaTypes: ['video'],
    mediaUrls: ['https://picsum.photos/seed/treemap/800/450'],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 7890,
    viewCount: 345000,
    bookmarkCount: 3210,
    postedAt: new Date('2024-11-28T16:00:00Z'),
    collectionIndices: [3, 4],
    tagIndices: [1, 2],
  },
  {
    content: 'Key insight from building in public: Your first 1000 users will teach you more than any amount of planning. Ship early, listen obsessively, iterate fast. The market will tell you what to build - if you\'re brave enough to listen. 💪',
    xPostId: 'seed_050',
    xAuthorName: 'Arvid Kahl',
    xAuthorUsername: 'arvidkahl',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 345,
    repostCount: 1890,
    likeCount: 9876,
    viewCount: 456000,
    bookmarkCount: 3789,
    postedAt: new Date('2024-11-27T11:00:00Z'),
    collectionIndices: [2],
    tagIndices: [3, 8],
  },
  {
    content: 'Embedding models comparison 2025: We tested OpenAI, Cohere, Nomic, BGE, and E5 on 12 retrieval tasks. TL;DR: For production RAG, BGE-M3 gives the best bang for buck. OpenAI ada-3 for convenience. Full benchmarks in the thread. 📊',
    xPostId: 'seed_051',
    xAuthorName: 'Nils Reimers',
    xAuthorUsername: 'nreimers',
    xAuthorAvatar: null,
    mediaTypes: ['photo'],
    mediaUrls: ['https://picsum.photos/seed/embeddings/800/400'],
    replyCount: 456,
    repostCount: 2345,
    likeCount: 12345,
    viewCount: 567000,
    bookmarkCount: 4567,
    postedAt: new Date('2024-11-26T10:00:00Z'),
    collectionIndices: [0, 3],
    tagIndices: [0, 1],
  },
  {
    content: 'Just discovered that CSS :has() can replace almost all JavaScript-based parent selectors. .card:has(img) { padding: 0; } - No more adding classes from JS. This is the CSS feature I\'ve been waiting 15 years for. 🎉',
    xPostId: 'seed_052',
    xAuthorName: 'Kevin Powell',
    xAuthorUsername: 'kevinjpowell',
    xAuthorAvatar: null,
    mediaTypes: [],
    mediaUrls: [],
    replyCount: 234,
    repostCount: 1234,
    likeCount: 6789,
    viewCount: 234000,
    bookmarkCount: 2654,
    postedAt: new Date('2024-11-25T14:30:00Z'),
    collectionIndices: [1],
    tagIndices: [2, 5],
  },
];

export async function seedDatabase() {
  console.log('🌱 Seeding database...');

  // Clean up existing data
  await db.activity.deleteMany();
  await db.bookmark.deleteMany();
  await db.tag.deleteMany();
  await db.collection.deleteMany();
  await db.session.deleteMany();
  await db.syncStatus.deleteMany();
  await db.user.deleteMany();

  // Create demo user
  const passwordHash = await hashPassword(DEMO_USER_PASSWORD);
  const user = await db.user.create({
    data: {
      email: DEMO_USER_EMAIL,
      name: 'Demo User',
      username: 'demouser',
      passwordHash,
    },
  });

  console.log(`✅ Created demo user: ${user.email}`);

  // Create collections
  const collections = [];
  for (let i = 0; i < COLLECTIONS.length; i++) {
    const col = COLLECTIONS[i];
    const collection = await db.collection.create({
      data: {
        userId: user.id,
        name: col.name,
        description: col.description,
        color: col.color,
        icon: col.icon,
        sortOrder: i,
      },
    });
    collections.push(collection);
  }

  console.log(`✅ Created ${collections.length} collections`);

  // Create tags
  const tags = [];
  for (const tagData of TAGS) {
    const tag = await db.tag.create({
      data: {
        userId: user.id,
        name: tagData.name,
        color: tagData.color,
      },
    });
    tags.push(tag);
  }

  console.log(`✅ Created ${tags.length} tags`);

  // Create bookmarks
  const bookmarks = [];
  for (const bookmarkData of BOOKMARKS) {
    const bookmark = await db.bookmark.create({
      data: {
        userId: user.id,
        xPostId: bookmarkData.xPostId,
        xAuthorId: `author_${bookmarkData.xAuthorUsername}`,
        xAuthorName: bookmarkData.xAuthorName,
        xAuthorUsername: bookmarkData.xAuthorUsername,
        xAuthorAvatar: bookmarkData.xAuthorAvatar,
        content: bookmarkData.content,
        mediaUrls: JSON.stringify(bookmarkData.mediaUrls),
        mediaTypes: JSON.stringify(bookmarkData.mediaTypes),
        replyCount: bookmarkData.replyCount,
        repostCount: bookmarkData.repostCount,
        likeCount: bookmarkData.likeCount,
        viewCount: bookmarkData.viewCount,
        bookmarkCount: bookmarkData.bookmarkCount,
        postedAt: bookmarkData.postedAt,
        isBookmarked: true,
        collections: {
          connect: bookmarkData.collectionIndices.map((i) => ({
            id: collections[i].id,
          })),
        },
        tags: {
          connect: bookmarkData.tagIndices.map((i) => ({
            id: tags[i].id,
          })),
        },
      },
    });
    bookmarks.push(bookmark);
  }

  console.log(`✅ Created ${bookmarks.length} bookmarks`);

  // Create activity records for the last 30 days
  const activityTypes = [
    'bookmark_save',
    'collection_create',
    'search',
    'bookmark_update',
    'sync_complete',
  ];

  for (let day = 0; day < 30; day++) {
    const activitiesPerDay = Math.floor(Math.random() * 8) + 2;
    for (let j = 0; j < activitiesPerDay; j++) {
      const date = new Date();
      date.setDate(date.getDate() - day);
      date.setHours(Math.floor(Math.random() * 14) + 8); // 8am - 10pm
      date.setMinutes(Math.floor(Math.random() * 60));

      const type = activityTypes[Math.floor(Math.random() * activityTypes.length)];
      const metadata: Record<string, unknown> = {};

      if (type === 'bookmark_save') {
        const randomBookmark = bookmarks[Math.floor(Math.random() * bookmarks.length)];
        metadata.bookmarkId = randomBookmark.id;
      } else if (type === 'collection_create') {
        const randomCollection = collections[Math.floor(Math.random() * collections.length)];
        metadata.collectionId = randomCollection.id;
      } else if (type === 'search') {
        const searchTerms = ['AI', 'design', 'startup', 'Python', 'React', 'ML', 'productivity'];
        metadata.query = searchTerms[Math.floor(Math.random() * searchTerms.length)];
      } else if (type === 'sync_complete') {
        metadata.syncedCount = Math.floor(Math.random() * 20) + 1;
      }

      await db.activity.create({
        data: {
          userId: user.id,
          type,
          metadata: JSON.stringify(metadata),
          createdAt: date,
        },
      });
    }
  }

  console.log('✅ Created activity records for the last 30 days');

  // Create sync status
  await db.syncStatus.create({
    data: {
      userId: user.id,
      lastSyncAt: new Date(),
      syncCount: bookmarks.length,
    },
  });

  console.log('✅ Created sync status');
  console.log('🎉 Seeding complete!');

  return {
    user: { email: user.email, name: user.name },
    collections: collections.length,
    tags: tags.length,
    bookmarks: bookmarks.length,
  };
}
